# Generated by Django 3.0.8 on 2020-10-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201015_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='sd_volume',
            new_name='sd_volume_max',
        ),
    ]
